### ISSUE TITLE
Bug: Exception from dependecy

### ISSUE THREAD

**Issue by atimin** [reduct-storage/reduct-py#47]
### What happened?

I mistook URL and got some HTML data instead of JSON and got the following exception:

```
Traceback (most recent call last):
  File "pydantic/main.py", line 539, in pydantic.main.BaseModel.parse_raw
  File "pydantic/parse.py", line 37, in pydantic.parse.load_str_bytes
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I think it is better to hide this exception behind ReductError.

### Version

v1.0.0

### OS

Linux, MacOS, Windows

### Snippet to repeat the bug

```python
from reduct import Client

client = Client("https://reduct-storage.dev")
await client.info()
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atimin** [comment]
Actually, the same problem with communication error:
```
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 8383)
```
